# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{raccoon}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marc Boeker"]
  s.date = %q{2009-11-28}
  s.description = %q{Use raccoon to debug you application (via a Ruby/Python/PHP client) or embed a JavaScript into your webpage and see what the users are doing.}
  s.email = %q{marc.boeker@onchestra.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "README.md"
  ]
  s.homepage = %q{http://github.com/marcboeker/raccoon}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{raccoon}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Live tracking of events, called in webapps}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jake>, [">= 0"])
    else
      s.add_dependency(%q<jake>, [">= 0"])
    end
  else
    s.add_dependency(%q<jake>, [">= 0"])
  end
end

